---
version: "2"
services:
  homeassistant:
    image: linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=America/Chicago # Specify a timezone to use
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
    volumes:
      - /home/tcude/docker/homeassistant/config:/config # Contains all relevant configuration files.
    devices:
      - /home/tcude/docker/homeassistant/devices:/path/to/device # For passing through USB, serial or gpio devices.
